### ISSUE TITLE
extraEnv variables does not work

### ISSUE THREAD

**Issue by Hashiphoto** [pmint93/helm-charts#60]
I have set up the following values for the chart:

```yaml
metabase:
  extraEnv:
    MB_REDIRECT_ALL_REQUESTS_TO_HTTPS: false
```

However, that environment variable is not getting passed to the pod. I only get the defaults:
```
JAVA_TIMEZONE : UTC
MB_COLORIZE_LOGS : true
MB_DB_TYPE : h2
MB_EMOJI_IN_LOGS : true
MB_JETTY_HOST : 0.0.0.0
MB_JETTY_PORT : 3000
MB_PASSWORD_COMPLEXITY : normal
MB_PASSWORD_LENGTH : 6
```

I have tried all sorts of other formats for `extraEnv`, but haven't gotten any to work. For example
```yaml
metabase:
  extraEnv:
    - MB_REDIRECT_ALL_REQUESTS_TO_HTTPS: false
```

```yaml
metabase:
  extraEnv:
    - name: MB_REDIRECT_ALL_REQUESTS_TO_HTTPS
      value: false
```

Both result in this error `warning: cannot overwrite table with non table for extraEnv (map[])` when running `helm template`

Any guidance would be appreciated. Thanks!
